{% set version = "0.14.0" %}

package:
  name: vale-styles-microsoft
  version: {{ version }}

source:
  - folder: Microsoft
    fn: vale-Microsoft-0.14.0.zip
    url: https://github.com/errata-ai/Microsoft/releases/download/v{{ version }}/Microsoft.zip
    sha256: eebf8f0713e72bf1e704a3370b4bea41f1fea2632be563df76296a22cecfcf4b
  - fn: LICENSE-vale-Microsoft-0.14.0
    url: https://raw.githubusercontent.com/errata-ai/Microsoft/v{{ version }}/LICENSE
    sha256: f661986be23c000812a439e03dfed8d16ff23117e8d1219fc2beb7cd01393640

build:
  noarch: generic
  number: 0

requirements:
  host:
    - vale
  run:
    - vale

test:
  requires:
    - pytest

about:
  home: https://github.com/errata-ai/Microsoft
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft rules for vale grammar and style checker

extra:
  recipe-maintainers:
    - bollwyvl
